# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='belongs_to', to='loginReg.User'),
        ),
    ]
