# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 18:48
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_book_year'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('run', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
