# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 18:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.DateField(default=datetime.date(2017, 4, 18)),
            preserve_default=False,
        ),
    ]
